version: "3.9"

services:

  app:
    image: node:17-alpine
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    entrypoint: node
    command: index.js
    depends_on:
      - etcd
      - nats
      - mysql
      - redis
    expose:
      - 8080
    environment:
      - NODE_ENV=local
      - TZ=America/Sao_Paulo
      - MOLECULER_CACHER=redis://redis:6379
      - MOLECULER_REGISTRY=etcd3://etcd:2379
      - MOLECULER_CHANNEL=redis://redis:6379
      - MOLECULER_TRANSPORTER=nats://nats:4222
      - DATABASE_URI=mysql://people:secret@mysql:3306/people

  nats:
    image: bitnami/nats
    expose:
      - 4222
    ports:
      - 4222:4222
    environment:
      - TZ=America/Sao_Paulo

  redis:
    image: bitnami/redis
    expose:
      - 6379
    ports:
      - 6379:6379
    environment:
      - TZ=America/Sao_Paulo
      - ALLOW_EMPTY_PASSWORD=yes

  etcd:
    image: bitnami/etcd
    expose:
      - 2379
    ports:
      - 2379:2379
    environment:
      - TZ=America/Sao_Paulo
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379

  mysql:
    image: bitnami/mysql:5.7
    volumes:
      - ff_mysql:/bitnami/mysql/data
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_USER=people
      - MYSQL_DATABASE=people
      - MYSQL_PASSWORD=secret
      - ROW_FORMAT=COMPRESSED
      - ALLOW_EMPTY_PASSWORD=yes

# volumes

volumes:
  ff_mysql: {}
