version: "3.9"

services:

  app:
    image: node:17-alpine
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    entrypoint: npm
    command: start
    depends_on:
      - etcd
      - nats
      - redis
      - mysql
      - postgresql
    expose:
      - 8080
    environment:
      - NODE_ENV=local
      - TZ=America/Sao_Paulo
      - MOLECULER_CACHER=redis://redis:6379
      - MOLECULER_REGISTRY=etcd3://etcd:2379
      - MOLECULER_CHANNEL=redis://redis:6379
      - MOLECULER_TRANSPORTER=nats://nats:4222
      - MYSQL_CONNECTION_STRING=mysql://ff-svc-moleculerjs:secret@mysql:3306/ff-svc-moleculerjs
      - POSTGRES_CONNECTION_STRING=postgresql://ff-svc-moleculerjs:secret@postgresql:5432/ff-svc-moleculerjs

  nats:
    image: bitnami/nats
    expose:
      - 4222
    ports:
      - 4222:4222
    environment:
      - TZ=America/Sao_Paulo

  redis:
    image: bitnami/redis
    expose:
      - 6379
    ports:
      - 6379:6379
    environment:
      - TZ=America/Sao_Paulo
      - ALLOW_EMPTY_PASSWORD=yes

  etcd:
    image: bitnami/etcd
    expose:
      - 2379
    ports:
      - 2379:2379
    environment:
      - TZ=America/Sao_Paulo
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379

  mysql:
    image: bitnami/mysql:5.7
    volumes:
      - ff_mysql:/bitnami/mysql/data
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_USER=ff-svc-moleculerjs
      - MYSQL_DATABASE=ff-svc-moleculerjs
      - MYSQL_PASSWORD=secret
      - ROW_FORMAT=COMPRESSED
      - ALLOW_EMPTY_PASSWORD=yes

  postgresql:
    image: bitnami/postgresql
    volumes:
      - ff_postgresql:/bitnami/mysql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRESQL_USERNAME=ff-svc-moleculerjs
      - POSTGRESQL_DATABASE=ff-svc-moleculerjs
      - POSTGRESQL_PASSWORD=secret

# volumes

volumes:
  ff_mysql: {}
  ff_postgresql: {}
