#@data/values
---
mysql:
  enabled: false
  values:
    primary:
      nodeSelector:
        - name: ff/arch 
          value: amd64
      persistence:
        size: 1Gi
        storageClass: longhorn-crypto-global

postgres:
  enabled: true
  values:
    primary:
      nodeSelector:
        - name: ff/arch 
          value: amd64
      persistence:
        size: 1Gi
        storageClass: longhorn-crypto-global

redis:
  enabled: true
  values:
    master:
      nodeSelector:
        - name: ff/arch 
          value: amd64

nats:
  enabled: true
  values:
    nodeSelector:
      - name: ff/arch 
        value: amd64

etcd:
  enabled: true
  values:
    nodeSelector:
      - name: ff/arch 
        value: amd64
