#@data/values
---
mysql:
  enabled: true
  values:
    primary:
      nodeSelector:
        - name: arch 
          value: amd64
      persistence:
        size: 1Gi
        storageClass: "longhorn"

postgres:
  enabled: true
  values:
    primary:
      persistence:
        size: 1Gi
        storageClass: "longhorn"

redis:
  enabled: true
  values:
    master:
      nodeSelector:
        "arch": "amd64"

nats:
  enabled: true
  values:
    nodeSelector:
      "arch": "amd64"

etcd:
  enabled: true
  values:
    nodeSelector:
      "arch": "amd64"
