#@data/values
---
mysql:
  enabled: false
  values:
    primary:
      persistence:
        size: 1Gi

postgres:
  enabled: false
  values:
    primary:
      persistence:
        size: 1Gi

redis:
  enabled: true

nats:
  enabled: true

etcd:
  enabled: true
