#@data/values
---
mysql:
  enabled: false
  values:
    primary:
      nodeSelector:
        - name: ff/arch 
          value: amd64
      persistence:
        enabled: false

postgres:
  enabled: true
  values:
    primary:
      nodeSelector:
        - name: ff/arch 
          value: amd64
      persistence:
        enabled: false

redis:
  enabled: true
  values:
    master:
      nodeSelector:
        - name: ff/arch 
          value: amd64

nats:
  enabled: true
  values:
    nodeSelector:
      - name: ff/arch 
        value: amd64

etcd:
  enabled: true
  values:
    nodeSelector:
      - name: ff/arch 
        value: amd64

rabbitmq:
  enabled: true
  values:
    nodeSelector:
      - name: ff/arch 
        value: amd64
    persistence:
      enabled: false
