#@data/values
---
mysql:
  enabled: true
  values:
    image:
      registry: ghcr.io
      repository: zcube/bitnami-compat/mysql
      tag: 8.0.30-debian-11-r19
    primary:
      persistence:
        enabled: false

redis:
  enabled: true
  values:
    image:
      registry: ghcr.io
      repository: zcube/bitnami-compat/redis
      tag: 7.0.4-debian-11-r19
