#@data/values
---
mysql:
  enabled: true
  values:
    primary:
      nodeSelector:
        - name: arch 
          value: amd64
      persistence:
        size: 1Gi
        storageClass: "longhorn"

postgres:
  enabled: true
  values:
    primary:
      persistence:
        size: 1Gi
        storageClass: "longhorn"

redis:
  enabled: true
  values:
    master:

nats:
  enabled: true
  values:

etcd:
  enabled: true
  values:
