#@data/values
---
mysql:
  enabled: true
  values:
    primary:
      persistence:
        enabled: false

postgres:
  enabled: true
  values:
    primary:
      persistence:
        enabled: false

redis:
  enabled: true

nats:
  enabled: true
  values:
    nodeSelector:
      - name: ff/arch 
        value: amd64

etcd:
  enabled: true

rabbitmq:
  enabled: true
  values:
    persistence:
      enabled: false
